NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/signca.cert
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/signca.cert
    OrganizationalUnitIdentifier: peer
